# Generated by Django 3.0.6 on 2020-05-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cas_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
