# Generated by Django 3.0.6 on 2020-05-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='journey_time',
            new_name='journey_datetime',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='journey_date',
        ),
    ]
