# Generated by Django 3.0.6 on 2020-05-23 20:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_auto_20200523_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='journey_datetime',
        ),
        migrations.AddField(
            model_name='trip',
            name='journey_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='trip',
            name='journey_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
