# Generated by Django 3.0.6 on 2020-05-24 22:48

import action.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0007_auto_20200524_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(choices=[['airport', 'Rajiv Gandhi International Airport'], ['railway-secunderabad', 'Secunderabad Railway Station'], ['railway-lingam', 'Lingampally Railway Station'], ['railway-begumpet', 'Begumpet Railway Station'], ['railway-nampally', 'Hyderabad Deccan Railway Station (Nampally)'], ['bus-mg', 'Mahatma Gandhi Bus Station'], ['college', 'IIIT Hyderabad Campus']], default='airport', max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='journey_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='journey_time',
            field=models.TimeField(default=action.models.def_time),
        ),
        migrations.AlterField(
            model_name='trip',
            name='source',
            field=models.CharField(choices=[['airport', 'Rajiv Gandhi International Airport'], ['railway-secunderabad', 'Secunderabad Railway Station'], ['railway-lingam', 'Lingampally Railway Station'], ['railway-begumpet', 'Begumpet Railway Station'], ['railway-nampally', 'Hyderabad Deccan Railway Station (Nampally)'], ['bus-mg', 'Mahatma Gandhi Bus Station'], ['college', 'IIIT Hyderabad Campus']], default='college', max_length=100),
        ),
    ]
